### ISSUE TITLE
iOS screen.orientation bug

### ISSUE THREAD

**Issue by clodewyks** [MarvinKlein1508/SignaturePad#19]
We've found a bug in production with this library and relates to the use of screen.orientation on iOS devices, we've seen this error in the past and got around it by using window.onorientationchange.

We've created a pull request for the fix that checks whether the browser has the screen.orientation API available, otherwise uses window.onorientationchange, the code has been tested and still executes the same `UpdateImage` function on orientation change on Windows, Android, and iOS.

Please review #18 

See stack trace below:

`Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: undefined is not an object (evaluating 'screen.orientation.onchange = function () {
    dotNetHelper.invokeMethodAsync('UpdateImage');
}')
module code@https://192.168.12.61:45457/_content/Blazor.SignaturePad/sigpad.interop.js:17:19

Microsoft.JSInterop.JSException: undefined is not an object (evaluating 'screen.orientation.onchange = function () {
    dotNetHelper.invokeMethodAsync('UpdateImage');
}')
module code@https://192.168.12.61:45457/_content/Blazor.SignaturePad/sigpad.interop.js:17:19
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at SignaturePad.SignaturePad.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'LoMYRTSLBGpnWSpcoTjEKmqxU_MI-Ys3QXZOA4gfrvU'.

Microsoft.JSInterop.JSException: undefined is not an object (evaluating 'screen.orientation.onchange = function () {
    dotNetHelper.invokeMethodAsync('UpdateImage');
}')
module code@https://192.168.12.61:45457/_content/Blazor.SignaturePad/sigpad.interop.js:17:19
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at SignaturePad.SignaturePad.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)`

**Comment by MarvinKlein1508** [comment]
Merged and sent to NuGet. Should be available shortly in V7.4.1
