### ISSUE TITLE
Issue: System.TimeoutException in SignaturePad.SignatureDataChangedAsync After Reconnection

### ISSUE THREAD

**Issue by HemeshSNHB** [MarvinKlein1508/SignaturePad#49]
**Description:**
I encountered a System.TimeoutException while using the SignaturePad component in my Blazor Server application. This exception occurs when the Blazor Server app disconnects from the server and then reconnects after some time. For example, if I minimize the app on my device, it disconnects, and upon reopening, it reconnects. Following the reconnection, I receive the following exception:

```
System.TimeoutException: Did not receive any data in the allotted time.
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.PipeReaderStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSDataStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Stream.<CopyToAsync>g__Core|29_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at SignaturePad.SignaturePad.SignatureDataChangedAsync()
```

**Steps to Reproduce:**
Initialize and use the SignaturePad component in a Blazor Server app.
Minimize the app on your device to simulate a disconnection.
Reopen the app, allowing it to reconnect to the server.
Observe the exception occurring after the reconnection.

**Expected Behavior:**
The method should complete its operation without timing out even after the app has reconnected.

**Actual Behavior:**
The method throws a System.TimeoutException after the app reconnects to the server.

**Environment:**
Blazor Server

**Version 7.5.0**

**Additional Context:**
The exception occurs consistently when the app disconnects and reconnects, suggesting it may be related to handling reconnection scenarios.

**Comment by MarvinKlein1508** [comment]
I've tried to reproduce your issue but I was not successful. Can you verify that I did everything correct?

https://github.com/user-attachments/assets/9e916371-95da-4b21-9d34-6d056e04b7d5

**Comment by HemeshSNHB** [comment]
Hi Marvin,

When I open the app on my mobile device and then minimize it, the app disconnects from the server. 

Upon maximizing the app, it attempts to reconnect. After a successful reconnection, I encounter the error when trying to sign in the SignaturePad area. I've included my code below for your review.

` <SignaturePad.SignaturePad @bind-Value="Signature" Options="_options" ShowClearButton="true"/>`

`private byte[] _signature = Array.Empty<byte>();`

` public byte[] Signature
 {
     get { return _signature; }
     set
     {
         _signature = value;
         CalculateMinAmount();
     }
 }`

**Comment by MarvinKlein1508** [comment]
Works fine for me. Can you maybe provide a ready to run repository?

https://github.com/user-attachments/assets/3a8967bb-eb8b-4613-b616-b62e46cd948e
